name: Publish1

on:
  pull_request:
      branches:
        - feat/refactor
  push:
      branches:
        - feat/refactor
  
jobs:
    build:
        # needs: test  # Ensure 'test' job completes successfully
        runs-on: ubuntu-latest

        steps:
          # - name: Check disk usage
          #   run: df -h

          # - name: Clean up disk space
          #   run: sudo rm -rf /tmp/* /var/tmp/*

          - name: Check out repository
            uses: actions/checkout@v4
            # with:
            #     fetch-depth: 1

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.11'  # Use the latest Python version or your preferred version for building

          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install poetry
                poetry install

          - name: Build package
            run: poetry build
            env:
                POETRY_VIRTUALENVS_IN_PROJECT: true

          - name: Upload package
            uses: actions/upload-artifact@v4
            with:
              name: built-package
              path: dist/*.whl  # or dist/*.tar.gz depending on your build

    publish:
        needs: build
        runs-on: ubuntu-latest

        steps:
          - name: Check out repository
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.11'  # Use the same version as used in build

          - name: Download package
            uses: actions/download-artifact@v4
            with:
              name: built-package
              path: ./dist

          - name: Publish to PyPI
            uses: JRubics/poetry-publish@v2.0
            with:
              pypi_token: ${{ secrets.PYPI_TOKEN }}
            env:
              POETRY_VIRTUALENVS_IN_PROJECT: true
